name: Update docs
on:
  push:
    branches:
      - [ $default-branch ]
    tags:
      - v*

jobs:
  update-docs:
    name: Update docs
    uses: unifyai/workflows/.github/workflows/docs.yml@master
    secrets: inherit
  